<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ["id" => 1, "district_name" => "ABIM"],
            ["id" => 2, "district_name" => "ADJUMANI"],
            ["id" => 3, "district_name" => "AGAGO"],
            ["id" => 4, "district_name" => "ALEBTONG"],
            ["id" => 5, "district_name" => "AMOLATAR"],
            ["id" => 6, "district_name" => "AMUDAT"],
            ["id" => 7, "district_name" => "AMURIA"],
            ["id" => 8, "district_name" => "AMURU"],
            ["id" => 9, "district_name" => "APAC"],
            ["id" => 10, "district_name" => "ARUA"],
            ["id" => 11, "district_name" => "BUDAKA"],
            ["id" => 12, "district_name" => "BUDUDA"],
            ["id" => 13, "district_name" => "BUGIRI"],
            ["id" => 14, "district_name" => "BUHWEJU"],
            ["id" => 15, "district_name" => "BUIKWE"],
            ["id" => 16, "district_name" => "BUKEDEA"],
            ["id" => 17, "district_name" => "BUKOMANSIMBI"],
            ["id" => 18, "district_name" => "BUKWO"],
            ["id" => 19, "district_name" => "BULAMBULI"],
            ["id" => 20, "district_name" => "BULIISA"],
            ["id" => 21, "district_name" => "BUNDIBUGYO"],
            ["id" => 22, "district_name" => "BUSHENYI"],
            ["id" => 23, "district_name" => "BUSIA"],
            ["id" => 24, "district_name" => "BUTALEJA"],
            ["id" => 25, "district_name" => "BUTAMBALA"],
            ["id" => 26, "district_name" => "BUVUMA"],
            ["id" => 27, "district_name" => "BUYENDE"],
            ["id" => 28, "district_name" => "DOKOLO"],
            ["id" => 29, "district_name" => "GOMBA"],
            ["id" => 30, "district_name" => "GULU"],
            ["id" => 31, "district_name" => "HOIMA"],
            ["id" => 32, "district_name" => "IBANDA"],
            ["id" => 33, "district_name" => "IGANGA"],
            ["id" => 34, "district_name" => "ISINGIRO"],
            ["id" => 35, "district_name" => "JINJA"],
            ["id" => 36, "district_name" => "KAABONG"],
            ["id" => 37, "district_name" => "KABALE"],
            ["id" => 38, "district_name" => "KABAROLE"],
            ["id" => 39, "district_name" => "KABERAMAIDO"],
            ["id" => 40, "district_name" => "KALANGALA"],
            ["id" => 41, "district_name" => "KALIRO"],
            ["id" => 42, "district_name" => "KALUNGU"],
            ["id" => 43, "district_name" => "KAMPALA"],
            ["id" => 44, "district_name" => "KAMULI"],
            ["id" => 45, "district_name" => "KAMWENGE"],
            ["id" => 46, "district_name" => "KANUNGU"],
            ["id" => 47, "district_name" => "KAPCHORWA"],
            ["id" => 48, "district_name" => "KASESE"],
            ["id" => 49, "district_name" => "KATAKWI"],
            ["id" => 50, "district_name" => "KAYUNGA"],
            ["id" => 51, "district_name" => "KIBAALE"],
            ["id" => 52, "district_name" => "KIBOGA"],
            ["id" => 53, "district_name" => "KIBUKU"],
            ["id" => 54, "district_name" => "KIRUHURA"],
            ["id" => 55, "district_name" => "KIRYANDONGO"],
            ["id" => 56, "district_name" => "KISORO"],
            ["id" => 57, "district_name" => "KITGUM"],
            ["id" => 58, "district_name" => "KOBOKO"],
            ["id" => 59, "district_name" => "KOLE"],
            ["id" => 60, "district_name" => "KOTIDO"],
            ["id" => 61, "district_name" => "KUMI"],
            ["id" => 62, "district_name" => "KWEEN"],
            ["id" => 63, "district_name" => "KYANKWANZI"],
            ["id" => 64, "district_name" => "KYEGEGWA"],
            ["id" => 65, "district_name" => "KYENJOJO"],
            ["id" => 66, "district_name" => "LAMWO"],
            ["id" => 67, "district_name" => "LIRA"],
            ["id" => 68, "district_name" => "LUUKA"],
            ["id" => 69, "district_name" => "LUWERO"],
            ["id" => 70, "district_name" => "LWENGO"],
            ["id" => 71, "district_name" => "LYANTONDE"],
            ["id" => 72, "district_name" => "MANAFWA"],
            ["id" => 73, "district_name" => "MARACHA"],
            ["id" => 74, "district_name" => "MASAKA"],
            ["id" => 75, "district_name" => "MASINDI"],
            ["id" => 76, "district_name" => "MAYUGE"],
            ["id" => 77, "district_name" => "MBALE"],
            ["id" => 78, "district_name" => "MBARARA"],
            ["id" => 79, "district_name" => "MITOOMA"],
            ["id" => 80, "district_name" => "MITYANA"],
            ["id" => 81, "district_name" => "MOROTO"],
            ["id" => 82, "district_name" => "MOYO"],
            ["id" => 83, "district_name" => "MPIGI"],
            ["id" => 84, "district_name" => "MUBENDE"],
            ["id" => 85, "district_name" => "MUKONO"],
            ["id" => 86, "district_name" => "NAKAPIRIPIRIT"],
            ["id" => 87, "district_name" => "NAKASEKE"],
            ["id" => 88, "district_name" => "NAKASONGOLA"],
            ["id" => 89, "district_name" => "NAMAYINGO"],
            ["id" => 90, "district_name" => "NAMUTUMBA"],
            ["id" => 91, "district_name" => "NAPAK"],
            ["id" => 92, "district_name" => "NEBBI"],
            ["id" => 93, "district_name" => "NGORA"],
            ["id" => 94, "district_name" => "NTOROKO"],
            ["id" => 95, "district_name" => "NTUNGAMO"],
            ["id" => 96, "district_name" => "NWOYA"],
            ["id" => 97, "district_name" => "OTUKE"],
            ["id" => 98, "district_name" => "OYAM"],
            ["id" => 99, "district_name" => "PADER"],
            ["id" => 100, "district_name" => "PALLISA"],
            ["id" => 101, "district_name" => "RAKAI"],
            ["id" => 102, "district_name" => "RUBIRIZI"],
            ["id" => 103, "district_name" => "RUKUNGIRI"],
            ["id" => 104, "district_name" => "SERERE"],
            ["id" => 105, "district_name" => "SHEEMA"],
            ["id" => 106, "district_name" => "SIRONKO"],
            ["id" => 107, "district_name" => "SOROTI"],
            ["id" => 108, "district_name" => "SSEMBABULE"],
            ["id" => 109, "district_name" => "TORORO"],
            ["id" => 110, "district_name" => "WAKISO"],
            ["id" => 111, "district_name" => "YUMBE"],
            ["id" => 112, "district_name" => "ZOMBO"],
            ["id" => 113, "district_name" => "Other"],
            ["id" => 114, "district_name" => "KYOTERA"],
            ["id" => 115, "district_name" => "Omoro"],
            ["id" => 116, "district_name" => "KAPELEBYONG"],
            ["id" => 117, "district_name" => "KIKUBE"],
            ["id" => 118, "district_name" => "KAZO"],
            ["id" => 119, "district_name" => "KIRUKURA"],
            ["id" => 120, "district_name" => "KARENGA"],
            ["id" => 121, "district_name" => "KALAKI"],
            ["id" => 122, "district_name" => "KWANIA"],
            ["id" => 123, "district_name" => "RUBANDA"],
            ["id" => 124, "district_name" => "KAGADI"],
            ["id" => 125, "district_name" => "RWAMPALA"],
            ["id" => 126, "district_name" => "NAMISINDWA"],
            ["id" => 127, "district_name" => "KAKUMIRO"],
            ["id" => 128, "district_name" => "PAKWACH"]
        ];

        DB::table('districts')->insert($data);
    }
}
