<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaperSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ["id" => 1, "paper_name" => "Anatomy and physiology l & First Aid", "year_of_study" => "Year 1 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "CN111"],
            ["id" => 2, "paper_name" => "Foundations of Nursing l and Basic Computer", "year_of_study" => "Year 1 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "CN112"],
            ["id" => 3, "paper_name" => "Personal and Communal Health & Microbiology", "year_of_study" => "Year 1 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "CN113"],
            ["id" => 4, "paper_name" => "Practical I", "year_of_study" => "Year 1 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "CN114"],
            ["id" => 5, "paper_name" => "Practical", "year_of_study" => "Year 1 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "CNU115"],
            ["id" => 6, "paper_name" => "Anatomy & physiology II", "year_of_study" => "Year 1 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "CN121"],
            ["id" => 7, "paper_name" => "Foundations of nursing ll, Sociology and psychology", "year_of_study" => "Year 1 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "CN122"],
            ["id" => 8, "paper_name" => "Primary Health Care", "year_of_study" => "Year 1 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "CN123"],
            ["id" => 9, "paper_name" => "Practical II", "year_of_study" => "Year 1 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "CN124"],
            ["id" => 10, "paper_name" => "Medical Nursing I and Pharmacology I ", "year_of_study" => "Year 2 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "CN211"],
            ["id" => 11, "paper_name" => "Surgical Nursing I and Gynaecology", "year_of_study" => "Year 2 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "CN212"],
            ["id" => 12, "paper_name" => "Paediatric Nursing I and Palliative Care Nursing", "year_of_study" => "Year 2 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "CN213"],
            ["id" => 13, "paper_name" => "Practical III", "year_of_study" => "Year 2 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "CN214"],
            ["id" => 14, "paper_name" => "Medical Nursing Il and Pharmacology Il", "year_of_study" => "Year 2 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "CN221"],
            ["id" => 15, "paper_name" => "Surgical Nursing ll and Paediatric Nursing Il", "year_of_study" => "Year 2 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "CN222"],
            ["id" => 16, "paper_name" => "Mental Health Nursing and Occupational Health  and Safety", "year_of_study" => "Year 2 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "CN223"],
            ["id" => 17, "paper_name" => "Practical IV", "year_of_study" => "Year 2 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "CN224"],
            ["id" => 18, "paper_name" => "Tropical Medicine and Surgical Nursing III", "year_of_study" => "Year 3 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "CN311"],
            ["id" => 19, "paper_name" => "Reproductive Health, Guidance and Counseling", "year_of_study" => "Year 3 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "CN312"],
            ["id" => 20, "paper_name" => "Health Services Management and Entrepreneurship", "year_of_study" => "Year 3 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "CN313"],
            ["id" => 21, "paper_name" => "Practical V", "year_of_study" => "Year 3 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "CN314"],
            ["id" => 22, "paper_name" => "Practical V", "year_of_study" => "Year 3 semester 1", "paper" => "Paper IV", "abbrev" => "P5", "code" => "CN315"],
            ["id" => 23, "paper_name" => "Anatomy and physiology l & First Aid", "year_of_study" => "Year 1 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "CM111"],
            ["id" => 24, "paper_name" => "Foundations of Nursing l and Basic Computer", "year_of_study" => "Year 1 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "CM112"],
            ["id" => 25, "paper_name" => "Personal and Communal Health & Microbiology", "year_of_study" => "Year 1 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "CM113"],
            ["id" => 26, "paper_name" => "Computer applications", "year_of_study" => "Year 1 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "CMW114"],
            ["id" => 27, "paper_name" => "Practical I", "year_of_study" => "Year 1 semester 1", "paper" => "Paper IV", "abbrev" => "P5", "code" => "CM114"],
            ["id" => 28, "paper_name" => "Anatomy & physiology II", "year_of_study" => "Year 1 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "CM121"],
            ["id" => 29, "paper_name" => "Foundations of Nursing ll, Sociology and psychology", "year_of_study" => "Year 1 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "CM122"],
            ["id" => 30, "paper_name" => "Primary Health Care", "year_of_study" => "Year 1 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "CM123"],
            ["id" => 31, "paper_name" => "Practical II", "year_of_study" => "Year 1 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "CM124"],
            ["id" => 32, "paper_name" => "Obstetrical Anatomy ", "year_of_study" => "Year 2 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "CM211"],
            ["id" => 33, "paper_name" => "Midwifery I and Pharmacology I", "year_of_study" => "Year 2 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "CM212"],
            ["id" => 34, "paper_name" => "Paediatric Nursing I Palliative Care Nursing", "year_of_study" => "Year 2 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "CM213"],
            ["id" => 35, "paper_name" => "Pediatrics 1 (normal baby)", "year_of_study" => "Year 2 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "CMW214"],
            ["id" => 36, "paper_name" => "Practical III", "year_of_study" => "Year 2 semester 1", "paper" => "Paper IV", "abbrev" => "P5", "code" => "CM214"],
            ["id" => 37, "paper_name" => "Midwifery II and Tropical Medicine", "year_of_study" => "Year 2 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "CM221"],
            ["id" => 38, "paper_name" => "Obstetric Pharmacology and Paediatric Nursing II", "year_of_study" => "Year 2 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "CM222"],
            ["id" => 39, "paper_name" => "Community Health Nursing, Occupational Health and Safety", "year_of_study" => "Year 2 semester 2", "paper" => "Paper III", "abbrev" => "p3", "code" => "CM223"],
            ["id" => 40, "paper_name" => "Occupational health and Community health 3( immunization)", "year_of_study" => "Year 2 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "CMW224"],
            ["id" => 41, "paper_name" => "Practical IV", "year_of_study" => "Year 2 semester 2", "paper" => "Paper IV", "abbrev" => "P5", "code" => "CM224"],
            ["id" => 42, "paper_name" => "Gynaecology and Reproductive Health", "year_of_study" => "Year 3 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "CM311"],
            ["id" => 43, "paper_name" => "Mental Health Nursing, Guidance and Counselling", "year_of_study" => "Year 3 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "CM312"],
            ["id" => 44, "paper_name" => "Health Service Management and Entrepreneurship", "year_of_study" => "Year 3 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "CM313"],
            ["id" => 45, "paper_name" => "Practical V", "year_of_study" => "Year 3 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "CM314"],
            ["id" => 46, "paper_name" => "Practical", "year_of_study" => "Year 3 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "CMW315"],
            ["id" => 47, "paper_name" => "Anatomy and physiology I & First aid", "year_of_study" => "Year 1 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "CCN111"],
            ["id" => 48, "paper_name" => "Foundations of nursing l, socio-psychology and basic Computer", "year_of_study" => "Year 1 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "CCN112"],
            ["id" => 49, "paper_name" => "Pharmacology I and Microbiology", "year_of_study" => "Year 1 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "CCN113"],
            ["id" => 50, "paper_name" => "Practical I", "year_of_study" => "Year 1 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "CCN114"],
            ["id" => 51, "paper_name" => "Practical", "year_of_study" => "Year 1 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "CCN115"],
            ["id" => 52, "paper_name" => "Anatomy and physiology Il", "year_of_study" => "Year 1 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "CCN121"],
            ["id" => 53, "paper_name" => "Foundations of Nursing II and Surgical Nursing", "year_of_study" => "Year 1 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "CCN122"],
            ["id" => 54, "paper_name" => "Medical Nursing I and Pharmacology II", "year_of_study" => "Year 1 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "CCN123"],
            ["id" => 55, "paper_name" => "Practical II", "year_of_study" => "Year 1 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "CCN124"],
            ["id" => 56, "paper_name" => "Medical Nursing ll and Mental Health Nursing", "year_of_study" => "Year 2 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "CCN211"],
            ["id" => 57, "paper_name" => "Surgical nursing ll", "year_of_study" => "Year 2 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "CCN212"],
            ["id" => 58, "paper_name" => "Primary Health Care and Palliative Care Nursing", "year_of_study" => "Year 2 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "CCN213"],
            ["id" => 59, "paper_name" => "Practical III", "year_of_study" => "Year 2 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "CCN214"],
            ["id" => 60, "paper_name" => "Midwifery l", "year_of_study" => "Year 2 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "CCN221"],
            ["id" => 61, "paper_name" => "Gynaecology", "year_of_study" => "Year 2 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "CCN222"],
            ["id" => 62, "paper_name" => "Reproductive health l", "year_of_study" => "Year 2 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "CCN223"],
            ["id" => 63, "paper_name" => "Practical IV", "year_of_study" => "Year 2 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "CCN224"],
            ["id" => 64, "paper_name" => "Midwifery ll & Reproductive health ll", "year_of_study" => "Year 3 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "CCN311"],
            ["id" => 65, "paper_name" => "Paediatrics Nursing and Community Health Nursing", "year_of_study" => "Year 3 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "CCN312"],
            ["id" => 66, "paper_name" => "Health Services Management and Entrepreneurship", "year_of_study" => "Year 3 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "CCN313"],
            ["id" => 67, "paper_name" => "Practical V", "year_of_study" => "Year 3 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "CCN314"],
            ["id" => 68, "paper_name" => "Anatomy and physiology I, First aid", "year_of_study" => "Year 1 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "CMHN111"],
            ["id" => 69, "paper_name" => "Foundations of nursing l, sociology, & psychology l and Basic Computer", "year_of_study" => "Year 1 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "CMHN112"],
            ["id" => 70, "paper_name" => "Psychiatric Nuring I Microbiology, Personal and Communal Health", "year_of_study" => "Year 1 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "CMHN113"],
            ["id" => 71, "paper_name" => "Practical I", "year_of_study" => "Year 1 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "CMHN114"],
            ["id" => 72, "paper_name" => "Computer applications (to be discussed)", "year_of_study" => "Year 1 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "CMH115"],
            ["id" => 73, "paper_name" => "Research", "year_of_study" => "Year 3 semester 2", "paper" => "Paper VI", "abbrev" => "P6", "code" => "DM326"],
            ["id" => 74, "paper_name" => "Anatomy and physiology Il", "year_of_study" => "Year 1 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "CMHN121"],
            ["id" => 75, "paper_name" => "Foundations of Nursing ll,  Psychology ll & Psychiatric Nursing II", "year_of_study" => "Year 1 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "CMHN122"],
            ["id" => 76, "paper_name" => "Medical - Surgical Nursing I and Pharmacology I", "year_of_study" => "Year 1 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "CMHN123"],
            ["id" => 77, "paper_name" => "Practical II", "year_of_study" => "Year 1 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "CMHN124"],
            ["id" => 78, "paper_name" => "Practical", "year_of_study" => "Year 1 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "CMH125"],
            ["id" => 79, "paper_name" => "Psychiatric Nursing III and Pharmacology II", "year_of_study" => "Year 2 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "CMHN211"],
            ["id" => 80, "paper_name" => "Medical-Surgical nursing ll", "year_of_study" => "Year 2 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "CMHN212"],
            ["id" => 81, "paper_name" => "Primary Health Care and Palliative Care Nursing", "year_of_study" => "Year 2 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "CMHN213"],
            ["id" => 82, "paper_name" => "Practical III", "year_of_study" => "Year 2 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "CMHN214"],
            ["id" => 83, "paper_name" => "Psychiatric Nursing IV and Psychotherapy", "year_of_study" => "Year 2 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "CMHN221"],
            ["id" => 84, "paper_name" => "Medical-Surgical nursing lll", "year_of_study" => "Year 2 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "CMHN222"],
            ["id" => 85, "paper_name" => "Gynaecology and Reproductive Health", "year_of_study" => "Year 2 semester 2", "paper" => "Paper III", "abbrev" => "p3", "code" => "CMHN223"],
            ["id" => 86, "paper_name" => "Practical IV", "year_of_study" => "Year 2 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "CMHN224"],
            ["id" => 87, "paper_name" => "Psychiatric Nursing V & Community Mental Health Nursing ", "year_of_study" => "Year 3 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "CMHN311"],
            ["id" => 88, "paper_name" => "Child Psychiatry and Occupational Health & Safety", "year_of_study" => "Year 3 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "CMHN312"],
            ["id" => 89, "paper_name" => "Health Services Management and Entrepreneurship", "year_of_study" => "Year 3 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "CMHN313"],
            ["id" => 90, "paper_name" => "Practical", "year_of_study" => "Year 3 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "CMHN314"],
            ["id" => 91, "paper_name" => "Foundations of Nursing I & Sociology and Psychology ", "year_of_study" => "Year 1 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "DN112"],
            ["id" => 92, "paper_name" => "Anatomy and Physiology I & First Aid ", "year_of_study" => "Year 1 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "DN111"],
            ["id" => 93, "paper_name" => "Guidance and Counselling and Basic Computer", "year_of_study" => "Year 1 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "DN113"],
            ["id" => 94, "paper_name" => "Microbiology, and Personal and Communal Health ", "year_of_study" => "Year 1 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DN114"],
            ["id" => 95, "paper_name" => "Practical I", "year_of_study" => "Year 1 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "DN115"],
            ["id" => 96, "paper_name" => "Research", "year_of_study" => "Year 3 semester 2", "paper" => "Paper VI", "abbrev" => "P6", "code" => "DN326"],
            ["id" => 97, "paper_name" => "Foundations of Nursing II", "year_of_study" => "Year 1 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "DN122"],
            ["id" => 98, "paper_name" => "Medical Nursing I & Pharmacology I", "year_of_study" => "Year 1 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "DN123"],
            ["id" => 99, "paper_name" => "Surgical Nursing I & Paediatric Nursing I ", "year_of_study" => "Year 1 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DN124"],
            ["id" => 100, "paper_name" => "Practicals II", "year_of_study" => "Year 1 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "DN125"],
            ["id" => 101, "paper_name" => "Medical Nursing II &Tropical Medicine ", "year_of_study" => "Year 2 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "DN211"],
            ["id" => 102, "paper_name" => "Surgical Nursing II ", "year_of_study" => "Year 2 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "DN212"],
            ["id" => 103, "paper_name" => "Gynaecology I & Reproductive Health I", "year_of_study" => "Year 2 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "DN213"],
            ["id" => 104, "paper_name" => "Mental Health Nursing I & Pharmacology II", "year_of_study" => "Year 2 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DN214"],
            ["id" => 105, "paper_name" => "Practical III", "year_of_study" => "Year 2 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "DN215"],
            ["id" => 106, "paper_name" => "Foundations of Nursing III", "year_of_study" => "Year 2 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "DN221"],
            ["id" => 107, "paper_name" => "Medical Nursing III  ", "year_of_study" => "Year 2 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "DN222"],
            ["id" => 108, "paper_name" => "Surgical Nursing III & Paediatric Nursing II", "year_of_study" => "Year 2 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "DN223"],
            ["id" => 109, "paper_name" => "Mental Health Nursing II and Pharmacology III  ", "year_of_study" => "Year 2 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DN224"],
            ["id" => 110, "paper_name" => "Practical IV", "year_of_study" => "Year 2 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "DN225"],
            ["id" => 111, "paper_name" => "Primary Health Care and Community Based Health Care", "year_of_study" => "Year 3 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "DN311"],
            ["id" => 112, "paper_name" => "Applied Research and Teaching Methodology", "year_of_study" => "Year 3 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "DN312"],
            ["id" => 113, "paper_name" => "Palliative Care Nursing", "year_of_study" => "Year 3 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "DN313"],
            ["id" => 114, "paper_name" => "Disaster Management and Occupational Health and Safety", "year_of_study" => "Year 3 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DN314"],
            ["id" => 115, "paper_name" => "Research Report", "year_of_study" => "Year 3 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "DCN325"],
            ["id" => 116, "paper_name" => "Paediatric Nursing III", "year_of_study" => "Year 3 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "DN321"],
            ["id" => 117, "paper_name" => "Gynaecology II and Reproductive Health II", "year_of_study" => "Year 3 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "DN322"],
            ["id" => 118, "paper_name" => "Health Services Management and Entrepreneurship", "year_of_study" => "Year 3 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "DN323"],
            ["id" => 119, "paper_name" => "Practical VI", "year_of_study" => "Year 3 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DN324"],
            ["id" => 120, "paper_name" => "Research Report", "year_of_study" => "Year 3 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "DN325"],
            ["id" => 121, "paper_name" => "Midwifery III", "year_of_study" => "Year 3 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "DM311"],
            ["id" => 122, "paper_name" => "Foundations of Nursing I, Sociology and Psychology", "year_of_study" => "Year 1 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "DM112"],
            ["id" => 123, "paper_name" => "Guidance and Counsellimg and Basic Computer", "year_of_study" => "Year 1 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "DM113"],
            ["id" => 124, "paper_name" => "Microbiology and Personal and Communal Health", "year_of_study" => "Year 1 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DM114"],
            ["id" => 125, "paper_name" => "Disaster Management, Occupational Health and Safety", "year_of_study" => "Year 3 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DM314"],
            ["id" => 126, "paper_name" => "Anatomy and Physiology I and First Aid", "year_of_study" => "Year 1 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "DCN111"],
            ["id" => 127, "paper_name" => "Foundations of Nursing I", "year_of_study" => "Year 1 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "DCN112"],
            ["id" => 128, "paper_name" => "Socio-Psychology and Basic Computer", "year_of_study" => "Year 1 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "DCN113"],
            ["id" => 129, "paper_name" => "Microbiology I", "year_of_study" => "Year 1 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DCN114"],
            ["id" => 130, "paper_name" => "Practical I", "year_of_study" => "Year 1 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "DCN115"],
            ["id" => 131, "paper_name" => "Anatomy and Physiology I and First Aid", "year_of_study" => "Year 1 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "DM111"],
            ["id" => 132, "paper_name" => "Foundations of Nursing I, Sociology and Psychology", "year_of_study" => "Year 1 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "DMHN112"],
            ["id" => 133, "paper_name" => "Microbiology and Basic Computer", "year_of_study" => "Year 1 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "DMHN113"],
            ["id" => 134, "paper_name" => "Psychiatric Nursing", "year_of_study" => "Year 1 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DMHN114"],
            ["id" => 135, "paper_name" => "Practical I", "year_of_study" => "Year 1 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "DMHN115"],
            ["id" => 136, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 1 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "DN121"],
            ["id" => 137, "paper_name" => "Foundations of Nursing II", "year_of_study" => "Year 1 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "DN122"],
            ["id" => 138, "paper_name" => "Medical Nursing I and Pharmacology", "year_of_study" => "Year 1 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "DN123"],
            ["id" => 139, "paper_name" => "Surgical Nursing I and Peadiatric Nursing I", "year_of_study" => "Year 1 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DN124"],
            ["id" => 140, "paper_name" => "Practical II", "year_of_study" => "Year 1 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "DN125"],
            ["id" => 141, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 1 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "DM121"],
            ["id" => 142, "paper_name" => "Foundations of Nursing II", "year_of_study" => "Year 1 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "DM122"],
            ["id" => 143, "paper_name" => "Pharmacology I", "year_of_study" => "Year 1 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "DM123"],
            ["id" => 144, "paper_name" => "Community Health ", "year_of_study" => "Year 1 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DM124"],
            ["id" => 145, "paper_name" => "Practical II", "year_of_study" => "Year 1 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "DM125"],
            ["id" => 146, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 1 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "DCN121"],
            ["id" => 147, "paper_name" => "Foundations of Nursing II and microbiology II", "year_of_study" => "Year 1 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "DCN122"],
            ["id" => 148, "paper_name" => "Pharmacology I", "year_of_study" => "Year 1 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "DCN123"],
            ["id" => 149, "paper_name" => "Mental Health Nursing I and Community Health Nursing I", "year_of_study" => "Year 1 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DCN124"],
            ["id" => 150, "paper_name" => "Practical II", "year_of_study" => "Year 1 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "DCN125"],
            ["id" => 151, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 1 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "DMHN121"],
            ["id" => 152, "paper_name" => "Foundations of Nursing II", "year_of_study" => "Year 1 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "DMHN122"],
            ["id" => 153, "paper_name" => "Psychiatric Nursing II", "year_of_study" => "Year 1 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "DMHN123"],
            ["id" => 154, "paper_name" => "Psychology II, Guidance and Counselling", "year_of_study" => "Year 1 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DMHN124"],
            ["id" => 155, "paper_name" => "Practical II", "year_of_study" => "Year 1 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "DMHN125"],
            ["id" => 156, "paper_name" => "Anatomy and Physiology I and First Aid", "year_of_study" => "Year 1 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "DMHN111"],
            ["id" => 157, "paper_name" => "Midwifery I, Paediatric Nursing II and Reproductive Health", "year_of_study" => "Year 2 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "DCN221"],
            ["id" => 158, "paper_name" => "Medical Nursing II and Pharmacology III", "year_of_study" => "Year 2 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "DCN222"],
            ["id" => 159, "paper_name" => "Surgical Nursing II, gynaecology and Health Service management I", "year_of_study" => "Year 2 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "DCN223"],
            ["id" => 160, "paper_name" => "Mental Health Nursing III and Community Health Nursing III", "year_of_study" => "Year 2 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DCN224"],
            ["id" => 161, "paper_name" => "Practical IV", "year_of_study" => "Year 2 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "DCN225"],
            ["id" => 162, "paper_name" => "Obstetric Anatomy and paediatric Nursing I", "year_of_study" => "Year 2 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "DCN211"],
            ["id" => 163, "paper_name" => "Medical Nursing I and Pharmacology II", "year_of_study" => "Year 2 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "DCN212"],
            ["id" => 164, "paper_name" => "Surgical nursing I and Foundations of Nursing III", "year_of_study" => "Year 2 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "DCN213"],
            ["id" => 165, "paper_name" => "Mental Health Nursing II and Community Health Nursing II", "year_of_study" => "Year 2 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DCN214"],
            ["id" => 166, "paper_name" => "Practical III", "year_of_study" => "Year 2 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "DCN215"],
            ["id" => 167, "paper_name" => "Midwifery II", "year_of_study" => "Year 3 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "DCN311"],
            ["id" => 168, "paper_name" => "Applied Research and Teaching Methodology and Community health Nursing IV", "year_of_study" => "Year 3 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "DCN312"],
            ["id" => 169, "paper_name" => "Medical Nursing III and Mental Health Nursing IV", "year_of_study" => "Year 3 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "DCN313"],
            ["id" => 170, "paper_name" => "Surgical Nursing III, Health Services managemnt II and Entrepreneurship", "year_of_study" => "Year 3 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DCN314"],
            ["id" => 171, "paper_name" => "Practical V", "year_of_study" => "Year 3 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "DCN315"],
            ["id" => 172, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 3 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "DCN321"],
            ["id" => 173, "paper_name" => "Health Services Management and Entrepreneurship", "year_of_study" => "Year 3 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "DM323"],
            ["id" => 174, "paper_name" => "Paediatric Nursing II", "year_of_study" => "Year 3 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "DM322"],
            ["id" => 175, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 3 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "DM323"],
            ["id" => 176, "paper_name" => "Practical VI", "year_of_study" => "Year 3 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DM324"],
            ["id" => 177, "paper_name" => "Research Report", "year_of_study" => "Year 3 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "DM325"],
            ["id" => 178, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 3 semester 2", "paper" => "Paper VI", "abbrev" => "P6", "code" => "DM326"],
            ["id" => 179, "paper_name" => "Practical III", "year_of_study" => "Year 2 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "DM215"],
            ["id" => 180, "paper_name" => "Midwifery I", "year_of_study" => "Year 2 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "DM212"],
            ["id" => 181, "paper_name" => "Gynecology I and Reproductive Health I", "year_of_study" => "Year 2 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "DM213"],
            ["id" => 182, "paper_name" => "Mental Health and Pharmacology II", "year_of_study" => "Year 2 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DM214"],
            ["id" => 183, "paper_name" => "Midwfiery IV", "year_of_study" => "Year 3 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "DM321"],
            ["id" => 184, "paper_name" => "Obstetric Anatomy", "year_of_study" => "Year 2 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "DM211"],
            ["id" => 185, "paper_name" => "Practical I", "year_of_study" => "Year 1 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "DM115"],
            ["id" => 186, "paper_name" => "Applied Research and Teaching Methodology", "year_of_study" => "Year 3 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "DM312"],
            ["id" => 187, "paper_name" => "Palliative Care Nursing", "year_of_study" => "Year 3 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "DM313"],
            ["id" => 188, "paper_name" => "Practical V", "year_of_study" => "Year 3 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "DM315"],
            ["id" => 189, "paper_name" => "Psychiatric Nursing III", "year_of_study" => "Year 2 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "DMHN211"],
            ["id" => 190, "paper_name" => "Medical- Surgical Nursing I", "year_of_study" => "Year 2 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "DMHN212"],
            ["id" => 191, "paper_name" => "Pharmacology I", "year_of_study" => "Year 2 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "DMHN213"],
            ["id" => 192, "paper_name" => "Paediatrics Nursing I", "year_of_study" => "Year 2 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DMHN214"],
            ["id" => 193, "paper_name" => "PRACTICAL III", "year_of_study" => "Year 2 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "DMHN215"],
            ["id" => 194, "paper_name" => "Medical -Surgical Nursing II", "year_of_study" => "Year 2 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "DMHN221"],
            ["id" => 195, "paper_name" => "Pharmacology II", "year_of_study" => "Year 2 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "DMHN222"],
            ["id" => 196, "paper_name" => "Child Psychiatry", "year_of_study" => "Year 2 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "DMHN223"],
            ["id" => 197, "paper_name" => "Practical IV", "year_of_study" => "Year 2 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "DMHN225"],
            ["id" => 198, "paper_name" => "Occupational Therapy and Mental Health Rehabilitation", "year_of_study" => "Year 3 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "DMHN311"],
            ["id" => 199, "paper_name" => "Applied Research and Teaching Methodology", "year_of_study" => "Year 3 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "DMHN312"],
            ["id" => 200, "paper_name" => "Health Serivces Management I", "year_of_study" => "Year 3 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DMHN314"],
            ["id" => 201, "paper_name" => "Practical v", "year_of_study" => "Year 3 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "DMHN315"],
            ["id" => 202, "paper_name" => "Community Mental Health Nursing", "year_of_study" => "Year 3 semester 2", "paper" => "Paper I", "abbrev" => "PI", "code" => "DMHN321"],
            ["id" => 203, "paper_name" => "Palliative Care Nursing , Occupational Health and Safety", "year_of_study" => "Year 3 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "DMHN322"],
            ["id" => 204, "paper_name" => "Health Serivces Management II and entrepreneurship", "year_of_study" => "Year 3 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "DMHN323"],
            ["id" => 205, "paper_name" => "ANTOMY", "year_of_study" => "Year 3 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DMHN324"],
            ["id" => 206, "paper_name" => "Practical VI", "year_of_study" => "Year 3 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "DMHN325"],
            ["id" => 207, "paper_name" => "Research", "year_of_study" => "Year 3 semester 2", "paper" => "Paper VI", "abbrev" => "P6", "code" => "DMHN326"],
            ["id" => 208, "paper_name" => "Primary Health Care", "year_of_study" => "Year 3 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "DMHN313"],
            ["id" => 209, "paper_name" => "Paediatric Nursing II", "year_of_study" => "Year 2 semester 2", "paper" => "Paper IV", "abbrev" => "p4", "code" => "DMHN224"],
            ["id" => 210, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 2 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "DMEL211"],
            ["id" => 211, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 2 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "DMEL 212"],
            ["id" => 212, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 2 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "DMEL 213"],
            ["id" => 213, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 2 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DMEL 214"],
            ["id" => 214, "paper_name" => "Practical", "year_of_study" => "Year 2 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "DMEL 215"],
            ["id" => 215, "paper_name" => "Midwifery IV", "year_of_study" => "Year 2 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "DMEL 221"],
            ["id" => 216, "paper_name" => "Paediatric Nursing I", "year_of_study" => "Year 2 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "DMEL 222"],
            ["id" => 217, "paper_name" => "Health Services Management and Entrepreneurship", "year_of_study" => "Year 2 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "DMEL 223"],
            ["id" => 218, "paper_name" => "\tPractical VI", "year_of_study" => "Year 2 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DMEL 224"],
            ["id" => 219, "paper_name" => "Research Report", "year_of_study" => "Year 2 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "DMEL 225"],
            ["id" => 220, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 2 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "DME 221"],
            ["id" => 221, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 2 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "DME 222"],
            ["id" => 222, "paper_name" => "Midwifery II", "year_of_study" => "Year 2 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "DM221"],
            ["id" => 223, "paper_name" => "Paediatric Nursing I", "year_of_study" => "Year 2 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "DM222"],
            ["id" => 224, "paper_name" => "Gynaecology II and Reproductive Health II", "year_of_study" => "Year 2 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "DM223"],
            ["id" => 225, "paper_name" => "Tropical Medicine", "year_of_study" => "Year 2 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DM224"],
            ["id" => 226, "paper_name" => "Prcatical IV", "year_of_study" => "Year 2 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "DM 225"],
            ["id" => 227, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 2 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "DME 223"],
            ["id" => 228, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 2 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DME 224"],
            ["id" => 229, "paper_name" => "Practical", "year_of_study" => "Year 2 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "DME 225"],
            ["id" => 230, "paper_name" => "Anatomy and Physiology related to child development and Normal Child", "year_of_study" => "Year 2 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "DPCHN221"],
            ["id" => 231, "paper_name" => "Foundations of Paediatric Nursing and Primary health Care", "year_of_study" => "Year 2 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "DPCHN222"],
            ["id" => 232, "paper_name" => "Paediatric pharmacology and Child Nutrition", "year_of_study" => "Year 2 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "DPCHN223"],
            ["id" => 233, "paper_name" => "Paediatric Psychology", "year_of_study" => "Year 2 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DPCHN224"],
            ["id" => 234, "paper_name" => "Practical I", "year_of_study" => "Year 2 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "DPCHN225"],
            ["id" => 235, "paper_name" => "Medical Nursing IV and Palliative Care Nursing", "year_of_study" => "Year 3 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "DCN322"],
            ["id" => 236, "paper_name" => "Surgical Nursing IV, Occupational Health and Safety ", "year_of_study" => "Year 3 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "DCN323"],
            ["id" => 237, "paper_name" => "Practical VI", "year_of_study" => "Year 3 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DCN324"],
            ["id" => 238, "paper_name" => "Research Report", "year_of_study" => "Year 3 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "DCNE 215"],
            ["id" => 239, "paper_name" => "Practical VII", "year_of_study" => "Year 3 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "DNE315"],
            ["id" => 240, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 3 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "DPCHN311"],
            ["id" => 241, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 3 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "DPCHN312"],
            ["id" => 242, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 3 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "DPCHN313"],
            ["id" => 243, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 3 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DPCHN314"],
            ["id" => 244, "paper_name" => "Practical II", "year_of_study" => "Year 3 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "DPCHN315"],
            ["id" => 245, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 3 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "DPCHN321"],
            ["id" => 246, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 3 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "DPCHN322"],
            ["id" => 247, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 3 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "DPCHN323"],
            ["id" => 248, "paper_name" => "Practical III", "year_of_study" => "Year 3 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DPCHN324"],
            ["id" => 249, "paper_name" => "Research Report", "year_of_study" => "Year 3 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "DPCHN325"],
            ["id" => 250, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 3 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "DPHN321"],
            ["id" => 251, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 3 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "DPHN322"],
            ["id" => 252, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 3 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "DPHN323"],
            ["id" => 253, "paper_name" => "Practical I", "year_of_study" => "Year 3 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DPHN324"],
            ["id" => 254, "paper_name" => "Research Report", "year_of_study" => "Year 3 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "DPHN325"],
            ["id" => 255, "paper_name" => "Foundations of Palliative Care, Ethical and Legal issues in Palliative Care", "year_of_study" => "Year 1 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "ADPCN 111"],
            ["id" => 256, "paper_name" => "Ethics and legal issues in Palliative Care, Psychosocial issues and team work", "year_of_study" => "Year 1 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "ADPCN 112"],
            ["id" => 257, "paper_name" => "Research methods and Nursing Informatics", "year_of_study" => "Year 1 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "ADPCN 113"],
            ["id" => 258, "paper_name" => "Pain Assessment and Management", "year_of_study" => "Year 1 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "ADPCN 114"],
            ["id" => 259, "paper_name" => "Practical I", "year_of_study" => "Year 1 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "ADPCN 115"],
            ["id" => 260, "paper_name" => "Symptom Control and Opioid use in Palliative Care", "year_of_study" => "Year 1 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "ADPCN 121"],
            ["id" => 261, "paper_name" => "\tSpiritual and Cultural issues in Palliative Care, Death, Dying, Grief and Bereavement", "year_of_study" => "Year 1 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "ADPCN 122"],
            ["id" => 262, "paper_name" => "Teaching Methodology and Mentorship ", "year_of_study" => "Year 1 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "ADPCN 123"],
            ["id" => 263, "paper_name" => "Palliative care in Disease Specific", "year_of_study" => "Year 1 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "ADPCN 124"],
            ["id" => 264, "paper_name" => "\tPractical II", "year_of_study" => "Year 1 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "ADPCN 125"],
            ["id" => 265, "paper_name" => "Midwifery I, Paediatric Nursing II and Reproductive Health", "year_of_study" => "Year 1 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "DCNE111"],
            ["id" => 266, "paper_name" => "Medical Nursing II and Pharmacology III", "year_of_study" => "Year 1 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "DCNE112"],
            ["id" => 267, "paper_name" => "Surgical Nursing II, gynaecology and Health Service management I", "year_of_study" => "Year 1 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "DCNE113"],
            ["id" => 268, "paper_name" => "Mental Health Nursing III and Community Health Nursing III", "year_of_study" => "Year 1 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DCNE114"],
            ["id" => 269, "paper_name" => "Practical IV", "year_of_study" => "Year 1 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "DCNE115"],
            ["id" => 270, "paper_name" => "Anatomy and Physiology related to child development and Normal Child", "year_of_study" => "Year 1 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "DPCHN111"],
            ["id" => 271, "paper_name" => "Foundations of Paediatric Nursing and Primary health Care", "year_of_study" => "Year 1 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "DPCHN112"],
            ["id" => 272, "paper_name" => "Paediatric pharmacology and Child Nutrition", "year_of_study" => "Year 1 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "DPCHN113"],
            ["id" => 273, "paper_name" => "Paediatric Psychology", "year_of_study" => "Year 1 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DPCHN114"],
            ["id" => 274, "paper_name" => "Practical I", "year_of_study" => "Year 1 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "DPCHN115"],
            ["id" => 275, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 1 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "DME111"],
            ["id" => 276, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 1 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "DME112"],
            ["id" => 277, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 1 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "DME113"],
            ["id" => 278, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 1 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DME114"],
            ["id" => 279, "paper_name" => "Practical I", "year_of_study" => "Year 1 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "DME115"],
            ["id" => 280, "paper_name" => "Foundations of Nursing III", "year_of_study" => "Year 1 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "DNE111"],
            ["id" => 281, "paper_name" => "Medical Nursing III ", "year_of_study" => "Year 1 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "DNE112"],
            ["id" => 282, "paper_name" => "Surgical Nursing III & Paediatric Nursing II", "year_of_study" => "Year 1 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "DNE113"],
            ["id" => 283, "paper_name" => "Mental Health Nursing II and Pharmacology III ", "year_of_study" => "Year 1 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DNE114"],
            ["id" => 284, "paper_name" => "Foundations of Nursing III", "year_of_study" => "Year 1 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "DNE115"],
            ["id" => 285, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 1 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "DMEL111"],
            ["id" => 286, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 1 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "DMEL112"],
            ["id" => 287, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 1 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "DMEL113"],
            ["id" => 288, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 1 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DMEL114"],
            ["id" => 289, "paper_name" => "Practical I", "year_of_study" => "Year 1 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "DMEL115"],
            ["id" => 290, "paper_name" => "Biostatistics, Demographic studies and Epidemiology", "year_of_study" => "Year 1 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "DPHN 111"],
            ["id" => 291, "paper_name" => "Applied Research and Teaching Methodology", "year_of_study" => "Year 1 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "DPHN 112"],
            ["id" => 292, "paper_name" => "Primary Health Care", "year_of_study" => "Year 1 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "DPHN113"],
            ["id" => 293, "paper_name" => "Public Health Nursing practices and , Occupational Health and Safety", "year_of_study" => "Year 1 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DPHN114"],
            ["id" => 294, "paper_name" => "Practical I", "year_of_study" => "Year 1 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "DPHN115"],
            ["id" => 295, "paper_name" => "Medical -Surgical Nursing II", "year_of_study" => "Year 1 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "DMHNE111"],
            ["id" => 296, "paper_name" => "Pharmacology II", "year_of_study" => "Year 1 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "DMHNE112"],
            ["id" => 297, "paper_name" => "Child Psychiatry", "year_of_study" => "Year 1 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "DMHNE113"],
            ["id" => 298, "paper_name" => "Paediatric Nursing II", "year_of_study" => "Year 1 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DMHNE114"],
            ["id" => 299, "paper_name" => "Practical I", "year_of_study" => "Year 1 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "DMHNE115"],
            ["id" => 300, "paper_name" => "Primary Health Care and Community Based Health Care", "year_of_study" => "Year 1 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "DNE 121"],
            ["id" => 301, "paper_name" => "Applied Research and Teaching Methodology", "year_of_study" => "Year 1 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "DNE 122"],
            ["id" => 302, "paper_name" => "Palliative Care Nursing", "year_of_study" => "Year 1 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "DNE 123"],
            ["id" => 303, "paper_name" => "Disaster Management and Occupational Health and Safety", "year_of_study" => "Year 1 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DNE 124"],
            ["id" => 304, "paper_name" => "Practical VII", "year_of_study" => "Year 1 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "DNE 125"],
            ["id" => 305, "paper_name" => "Midwifery III", "year_of_study" => "Year 1 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "DME121"],
            ["id" => 306, "paper_name" => "Applied Research and Teaching Methodology", "year_of_study" => "Year 1 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "DMEL 312"],
            ["id" => 307, "paper_name" => "Palliative Care Nursing", "year_of_study" => "Year 1 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "DMEL 123"],
            ["id" => 308, "paper_name" => "Disaster Management, Occupational Health and Safety", "year_of_study" => "Year 1 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DMEL 124"],
            ["id" => 309, "paper_name" => "Practical V", "year_of_study" => "Year 1 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "DMEL 125"],
            ["id" => 310, "paper_name" => "Midwifery II", "year_of_study" => "Year 3 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "DME 311"],
            ["id" => 311, "paper_name" => "Applied Research and Teaching Methodology", "year_of_study" => "Year 3 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "DME 312"],
            ["id" => 312, "paper_name" => "Paediatric Nursing I and Palliative Care Nursing", "year_of_study" => "Year 3 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "DME 313"],
            ["id" => 313, "paper_name" => "Disaster Management and Occupational Health and Safety", "year_of_study" => "Year 3 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DME 314"],
            ["id" => 314, "paper_name" => "Practical V", "year_of_study" => "Year 3 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "DME 315"],
            ["id" => 315, "paper_name" => "Midwifery II", "year_of_study" => "Year 1 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "DME 121"],
            ["id" => 316, "paper_name" => "Applied Research and Teaching Methodology", "year_of_study" => "Year 1 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "DME 122"],
            ["id" => 317, "paper_name" => "Paediatric Nursing I and Palliative Care Nursing", "year_of_study" => "Year 1 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "DME 123"],
            ["id" => 318, "paper_name" => "Disaster Management, Occupational Health and Safety", "year_of_study" => "Year 1 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DME 124"],
            ["id" => 319, "paper_name" => "Practical V", "year_of_study" => "Year 1 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "DME 125"],
            ["id" => 320, "paper_name" => "Midwifery II", "year_of_study" => "Year 1 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "DCNE 121"],
            ["id" => 321, "paper_name" => "Applied Research and Teaching Methodology and Community health Nursing IV", "year_of_study" => "Year 1 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "DCNE 122"],
            ["id" => 322, "paper_name" => "Medical Nursing III and Mental Health Nursing IV", "year_of_study" => "Year 1 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "DCNE 123"],
            ["id" => 323, "paper_name" => "Surgical Nursing III, Health Services managemnt II and Entrepreneurship", "year_of_study" => "Year 1 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DCNE 124"],
            ["id" => 324, "paper_name" => "Practical V", "year_of_study" => "Year 1 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "DCNE 125"],
            ["id" => 325, "paper_name" => "Occupational Therapy and Mental Health Rehabilitation", "year_of_study" => "Year 1 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "DMHNE 121"],
            ["id" => 326, "paper_name" => "Applied Research and Teaching Methodology", "year_of_study" => "Year 1 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "DMHNE 122"],
            ["id" => 327, "paper_name" => "Primary Health Care", "year_of_study" => "Year 1 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "DMHNE 123"],
            ["id" => 328, "paper_name" => "Health Serivces Management I", "year_of_study" => "Year 1 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DMHNE 124"],
            ["id" => 329, "paper_name" => "Practical V", "year_of_study" => "Year 1 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "DMHNE 125"],
            ["id" => 330, "paper_name" => "Paediatric Medical Nursing and Paediatric Psychiatry", "year_of_study" => "Year 1 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "DPCHNE 121"],
            ["id" => 331, "paper_name" => "Applied Research and Teaching Methodology", "year_of_study" => "Year 1 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "DPCHNE 122"],
            ["id" => 332, "paper_name" => "Paediatric Surgical Nursing and Paediatric HIV/Aids", "year_of_study" => "Year 1 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "DPCHNE 123"],
            ["id" => 333, "paper_name" => "Environmental Health and Epidemiology", "year_of_study" => "Year 1 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DPCHNE 124"],
            ["id" => 334, "paper_name" => "Practical II", "year_of_study" => "Year 1 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "DPCHNE 125"],
            ["id" => 335, "paper_name" => "Paediatric Nursing III", "year_of_study" => "Year 3 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "DNE 321"],
            ["id" => 336, "paper_name" => "Gynaecology II and Reproductive Health II", "year_of_study" => "Year 3 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "DNE 322"],
            ["id" => 337, "paper_name" => "Health Services Management and Entrepreneurship", "year_of_study" => "Year 3 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "DNE 323"],
            ["id" => 338, "paper_name" => "Practical VI", "year_of_study" => "Year 3 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DNE 324"],
            ["id" => 339, "paper_name" => "Research", "year_of_study" => "Year 3 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "DNE 325"],
            ["id" => 340, "paper_name" => "Primary Health Care and Community Based Health Care", "year_of_study" => "Year 3 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "DNE 311"],
            ["id" => 341, "paper_name" => "Applied Research and Teaching Methodology", "year_of_study" => "Year 3 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "DNE 312"],
            ["id" => 342, "paper_name" => "Palliative Care Nursing", "year_of_study" => "Year 3 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "DNE 313"],
            ["id" => 343, "paper_name" => "Disaster Management and Occupational Health and Safety", "year_of_study" => "Year 3 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DNE 314"],
            ["id" => 344, "paper_name" => "Foundations of Nursing III", "year_of_study" => "Year 2 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "DNE 221"],
            ["id" => 345, "paper_name" => "Medical Nursing III ", "year_of_study" => "Year 2 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "DNE 222"],
            ["id" => 346, "paper_name" => "Surgical Nursing III & Paediatric Nursing II", "year_of_study" => "Year 2 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "DNE 223"],
            ["id" => 347, "paper_name" => "Mental Health Nursing II and Pharmacology III ", "year_of_study" => "Year 2 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DNE 224"],
            ["id" => 348, "paper_name" => "Practical IV", "year_of_study" => "Year 2 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "DNE 225"],
            ["id" => 349, "paper_name" => "Midwifery III", "year_of_study" => "Year 3 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "DMEL 311"],
            ["id" => 350, "paper_name" => "Applied Research and Teaching Methodology", "year_of_study" => "Year 3 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "DMEL 312"],
            ["id" => 351, "paper_name" => "Palliative Care Nursing", "year_of_study" => "Year 3 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "DMEL 313"],
            ["id" => 352, "paper_name" => "Disaster Management, Occupational Health and Safety", "year_of_study" => "Year 3 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DMEL 314"],
            ["id" => 353, "paper_name" => "Practical V", "year_of_study" => "Year 3 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "DMEL 315"],
            ["id" => 354, "paper_name" => "Midwfiery IV", "year_of_study" => "Year 3 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "DMEL 321"],
            ["id" => 355, "paper_name" => "Paediatric Nursing II", "year_of_study" => "Year 3 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "DMEL 322"],
            ["id" => 356, "paper_name" => "Health Services Management and Entrepreneurship", "year_of_study" => "Year 3 semester 2", "paper" => "Paper III", "abbrev" => "P2", "code" => "DMEL 323"],
            ["id" => 357, "paper_name" => "Practical VI", "year_of_study" => "Year 3 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DMEL 324"],
            ["id" => 358, "paper_name" => "Research Report", "year_of_study" => "Year 3 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "DMEL 325"],
            ["id" => 359, "paper_name" => "Medical Nursing IV and Palliative Care Nursing", "year_of_study" => "Year 3 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "DCNE 322"],
            ["id" => 360, "paper_name" => "Surgical Nursing IV, Occupational Health and Safety ", "year_of_study" => "Year 3 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "DCNE 323"],
            ["id" => 361, "paper_name" => "Practical VI", "year_of_study" => "Year 3 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DCNE 324"],
            ["id" => 362, "paper_name" => "Research Report", "year_of_study" => "Year 3 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "DCNE 325"],
            ["id" => 363, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 3 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "DCNE 321"],
            ["id" => 364, "paper_name" => "Community Mental Health Nursing", "year_of_study" => "Year 3 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "DMHNE 321"],
            ["id" => 365, "paper_name" => "Palliative Care Nursing , Occupational Health and Safety", "year_of_study" => "Year 3 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "DMHNE 322"],
            ["id" => 366, "paper_name" => "Health Serivces Management II and entrepreneurship", "year_of_study" => "Year 3 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "DMHNE 323"],
            ["id" => 367, "paper_name" => "Practical VI", "year_of_study" => "Year 3 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DMHNE 324"],
            ["id" => 368, "paper_name" => "Research", "year_of_study" => "Year 3 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "DMHNE 325"],
            ["id" => 369, "paper_name" => "Practical V", "year_of_study" => "Year 3 semester 1", "paper" => "Paper V", "abbrev" => "pa", "code" => "DN 315"],
            ["id" => 370, "paper_name" => "Anatomy and Physiology II", "year_of_study" => "Year 2 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "DCNE 211"],
            ["id" => 371, "paper_name" => "Medical Nursing IV and Palliative Care Nursing", "year_of_study" => "Year 2 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "DCNE 212"],
            ["id" => 372, "paper_name" => "Surgical Nursing IV, Occupational Health and Safety ", "year_of_study" => "Year 2 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "DCNE 213"],
            ["id" => 373, "paper_name" => "Practical VI", "year_of_study" => "Year 2 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DCNE 214"],
            ["id" => 374, "paper_name" => "Research Report", "year_of_study" => "Year 2 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "DCNE 215"],
            ["id" => 375, "paper_name" => "Community Mental Health Nursing", "year_of_study" => "Year 2 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "DMHNE 211"],
            ["id" => 376, "paper_name" => "Palliative Care Nursing , Occupational Health and Safety", "year_of_study" => "Year 2 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "DMHNE 212"],
            ["id" => 377, "paper_name" => "Health Serivces Management II and entrepreneurship", "year_of_study" => "Year 2 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "DMHNE 213"],
            ["id" => 378, "paper_name" => "Practical VI", "year_of_study" => "Year 2 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DMHNE 214"],
            ["id" => 379, "paper_name" => "Research Report", "year_of_study" => "Year 2 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "DMHNE 215"],
            ["id" => 380, "paper_name" => "Midwfiery IV", "year_of_study" => "Year 2 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "DME 211"],
            ["id" => 381, "paper_name" => "Paediatric Nursing II", "year_of_study" => "Year 2 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "DME 212"],
            ["id" => 382, "paper_name" => "Health Services Management and Entrepreneurship", "year_of_study" => "Year 2 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "DME 213"],
            ["id" => 383, "paper_name" => "Practical VI", "year_of_study" => "Year 2 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DME 214"],
            ["id" => 384, "paper_name" => "Research Report", "year_of_study" => "Year 2 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "DME 215"],
            ["id" => 385, "paper_name" => "Paediatric Nursing III", "year_of_study" => "Year 2 semester 1", "paper" => "Paper I", "abbrev" => "P1", "code" => "DNE 211"],
            ["id" => 386, "paper_name" => "Gynaecology II and Reproductive Health II", "year_of_study" => "Year 2 semester 1", "paper" => "Paper II", "abbrev" => "P2", "code" => "DNE 212"],
            ["id" => 387, "paper_name" => "Health Services Management and Entrepreneurship", "year_of_study" => "Year 2 semester 1", "paper" => "Paper III", "abbrev" => "P3", "code" => "DNE 213"],
            ["id" => 388, "paper_name" => "Practical VI", "year_of_study" => "Year 2 semester 1", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DNE 214"],
            ["id" => 389, "paper_name" => "Research Report", "year_of_study" => "Year 2 semester 1", "paper" => "Paper V", "abbrev" => "P5", "code" => "DNE 215"],
            ["id" => 390, "paper_name" => "Midwifery III", "year_of_study" => "Year 2 semester 1", "paper" => "Paper I", "abbrev" => "PA", "code" => "DMEL 211"],
            ["id" => 391, "paper_name" => "Applied Research and Teaching Methodology", "year_of_study" => "Year 2 semester 1", "paper" => "Paper II", "abbrev" => "PA", "code" => "DMEL 212"],
            ["id" => 392, "paper_name" => "Palliative Care Nursing", "year_of_study" => "Year 2 semester 1", "paper" => "Paper III", "abbrev" => "PA", "code" => "DMEL 213"],
            ["id" => 393, "paper_name" => "Disaster Management, Occupational Health and Safety", "year_of_study" => "Year 2 semester 1", "paper" => "Paper IV", "abbrev" => "PA", "code" => "DMEL 214"],
            ["id" => 394, "paper_name" => "Practical V", "year_of_study" => "Year 2 semester 1", "paper" => "Paper V", "abbrev" => "PA", "code" => "DMEL 215"],
            ["id" => 395, "paper_name" => "Disease Surceillance and Reproductivr Health", "year_of_study" => "Year 1 semester 2", "paper" => "Paper I", "abbrev" => "P1", "code" => "DPHN 121"],
            ["id" => 396, "paper_name" => "Pallaitive Care Nursing", "year_of_study" => "Year 1 semester 2", "paper" => "Paper II", "abbrev" => "P2", "code" => "DPHN 112"],
            ["id" => 397, "paper_name" => "Health Services Management and Entrepreneurship", "year_of_study" => "Year 1 semester 2", "paper" => "Paper III", "abbrev" => "P3", "code" => "DPHN 123"],
            ["id" => 398, "paper_name" => "Practical II", "year_of_study" => "Year 1 semester 2", "paper" => "Paper IV", "abbrev" => "P4", "code" => "DPHN 124"],
            ["id" => 399, "paper_name" => "Research Report", "year_of_study" => "Year 1 semester 2", "paper" => "Paper V", "abbrev" => "P5", "code" => "DPHN 125"],
            ["id" => 400, "paper_name" => "Research Report", "year_of_study" => "Year 1 semester 2", "paper" => "Paper VI", "abbrev" => "", "code" => "ADPCN 126"]
        ];


        DB::table('papers')->insert($data);
    }
}
